<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DevToolsApp</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.CompanyName.DevToolsApp</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	<AndroidPackageFormat>apk</AndroidPackageFormat>

	<EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>

	<AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
	<AndroidEnableMultiDex>True</AndroidEnableMultiDex>
    <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
  </PropertyGroup>

  <!-- Подпись -->
  <PropertyGroup>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore Condition="'$(AndroidSigningKeyStore)' == ''">dev.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass Condition="'$(AndroidSigningStorePass)' == ''">123456</AndroidSigningStorePass>
    <AndroidSigningKeyAlias Condition="'$(AndroidSigningKeyAlias)' == ''">dev</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass Condition="'$(AndroidSigningKeyPass)' == ''">123456</AndroidSigningKeyPass>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
	<!-- Архитектура: используем переданную или по умолчанию под всё -->
	<RuntimeIdentifiers Condition="'$(RuntimeIdentifier)' == ''">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>

	<!-- Сжатие и удаление лишнего кода -->
	<PublishTrimmed>True</PublishTrimmed>
	<TrimMode>partial</TrimMode>
	<EnableAssemblyCompression>True</EnableAssemblyCompression>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Icon.png">
      <Link>Resources\drawable\Icon.png</Link>
    </AndroidResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevToolsApp\DevToolsApp.csproj" />
  </ItemGroup>
</Project>
